import Sidebar from "@/components/Sidebar";
import "../styles/index.css";
import cn from "classnames";
import { Inter, DM_Sans, Poppins } from "next/font/google";
import TabNavigator from "@/components/TabNavigator";
import {
  Bag,
  Email,
  Home,
  Instagram,
  LinkedIn,
  Profile,
  Store,
  Writing,
  X,
  Youtube,
} from "@/components/Icons";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-dm-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  {
    title: "Home",
    url: "/",
    icon: <Home />,
  },
  {
    title: "Projects",
    url: "/projects",
    icon: <Bag />,
  },
  {
    title: "Store",
    url: "/store",
    icon: <Store />,
  },
  {
    title: "About",
    url: "/about",
    icon: <Profile />,
  },
  {
    title: "Writings",
    url: "/writings",
    icon: <Writing />,
  },
  {
    title: "Contact",
    url: "/contact",
    icon: <Email />,
  },
];

const socials = [
  {
    url: "https://www.instagram.com/",
    icon: <Instagram />,
  },
  {
    url: "https://www.twitter.com/",
    icon: <X />,
  },
  {
    url: "https://www.youtube.com/",
    icon: <Youtube />,
  },
  {
    url: "https://www.linkedin.com/",
    icon: <LinkedIn />,
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Krafty Personal Template</title>
        <meta name="description" content="Personal template for creators." />
      </head>
      <body className={cn(inter.variable, poppins.variable, dmSans.variable)}>
        <main
          style={{
            display: "flex",
          }}
        >
          <Sidebar links={links} socials={socials} />
          <TabNavigator links={links} socials={socials} />
          {children}
        </main>
      </body>
    </html>
  );
}
